#+TITLE: About me

I am the founder of the now-retired Greybeard consulting, which previously consulted for companies mostly in the Web3 space. It now focuses on internal projects, including a chat application and the Map of Ageing. You can visit [our site.](https://greybeard.consulting/)

I'm currently a lead backend engineer at [[https://proof.trade][Proof]], a subsidiary of Drift. I previously worked as a senior distributed systems consultant at [[https://www.eclipse.xyz/][Eclipse Laboratories Inc]], where I researched modular blockchains and guided development of the canonical bridge "syzygy" between Ethereum and Solana. I also consulted for [[https://yz.social/][YZ.Social]] until April 2026. Before that, I was tech lead and product owner of [[https://iroha.tech/][Hyperledger Iroha v2]]. Before then, I studied Physical Natural Sciences at the [[https://www.cam.ac.uk/][University of Cambridge]] (MSci, 2020), where I worked on accelerated nested sampling for cosmological parameter estimation, and received medals at the International Physics Olympiad.

I'm an avid supporter of Free Software and was previously an associate member of the FSF. The current political climate and recent witch hunts led me to decide that I can work on free software more directly. Specifically I contribute to GNU Emacs, and am the author of some packages. More on that in the projects page.
