#+TITLE: My Dog Sirius
#+AUTHOR: Aleksandr Petrosyan
#+DATE: 2026-02-07
#+TAGS: Sirius
#+TAGS: Personal

This is a rather tough one to write.  Three years ago, me and my wife have given in to our long-standing desire to get a puppy.  We were looking through listings in a few places.  One stood out, as it was a mixed breed pup with blue eyes, and was to be given away for free.  I did not have a lot of money at that time, and was not fully intent on bringing the pup back.  You're not supposed to.  If you choose to pick up a pup, you earmark, and you get the house ready for the dog /before/ you agree to take them in.  To ease the transition it is also often customary to give the puppy smells: some of yours, some familiar, to both get ready for their (hopefully) forever home, but also to remind them of their not-so-long-ago right there mum and siblings.

We arrived at a squalid garage, where the pups were wallowing in their own faeces.  They were much too young to wean, but I had reasoned that the amount of damage caused by taking this one too early is negligible compared to the amount of damage caused to them just by being there.  I had come to the conclusion, that "it is better off with me".

I do not want to go into sentimental details just yet.  I do not know how much time we have left together, so I would like not to tempt fate tomorrow by writing an epitaph today.  I do believe that there has to be a written digital record of Sirius Barbas.

What I do want to point out is that my puppy had a good upbringing.  He wasn't /exactly/ my first dog, though technically he was the first dog I was wholly responsible for.  The same is true, to the same extent of my wife.  We knew most of what we were doing, but had to improvise too.  The result was an active, kind, smart and somewhat stubborn dog, that a great deal of discipline but was also allowed a great deal of freedom.  Sirius is free to go wherever he pleases, he has no shortage of good quality food, (often better quality than I had growing up), he is given an over-abundance of attention and play.

He is a rather large dog, and I knew full well, that this comes with problems.  They live a shorter average lifespan, though he is a mix of generally very healthy breeds, one has to take into account the local backyard breeding practices.  Despite my best efforts, we had /had/ to make emergency veterinary trips.  Of interest are three situations in which he had hurt his left hind leg.

Once he was walking with me.  He was socialising with an impressive circle of other dogs, and during what I consider to be regular play...  he hurt his leg.  I had taken him to the vet, who identified /nothing wrong/ with the dog.  I thought nothing of it, and reasoned that regardless of whether something was wrong with him, given that owning a pet is a luxury that few can afford, that if I asked if something were indeed wrong with him, they'd find something.

The second case was much more severe.  It was my wife walking him, and because of a rather complicated relationship with her, my parents and myself, I cannot say for certain what exactly happened.  All I can say, is I assumed either that one of the strays bit his ankle, or that the wet tile[fn:1] proved too slippery and my dog had a sprain.  We took him to a nearby vet, on foot, primarily because lacking a personal car, it is not possible to drive him there, more on that in another article.  An X-Ray was taken, and nothing wrong was identified.

One year later...  we leave my dog with my parents, something which happens rather infrequently, as I usually accompany him, and we don't overstay our welcome.  He conveys a signal: he has diarrhoea.  So I let him loose, and notice a limp.  The day after I'm woken up by my wife, stating that his leg is swollen.

This was... and I did not know it at the time...  the last time I'd see him whole and healthy.  We took him to his vet, who said "oh probably a torn ligament", and sent us on our way to find another veterinary orthopaedics specialist.  We find a shockingly early appointment and decide not to take our time.  The sooner we were out of the woods, the sooner we could get "back to normal".

What followed are without a doubt the worst two months of my life.  There is heated competition for that title.  The fact that this thing in particular won, should be telling.

We could not, and still have not, gotten a diagnosis.  All we know is what is blindingly obvious: the dog has a large tumour in his leg.  He's in constant pain.  He can't sleep, because his favourite spots: the couch and the cushioned armchair, are places he cannot climb into without his swollen and dysfunctional leg getting snagged and causing him excruciating pain.

We don't know if it's a benign tumour, some form of auto-immune disease, or a death sentence in the form of Osteo-sarcoma.  All we know is that Friday last week we had a more-or-less healthy dog, which used his sick leg a little less, but was mostly fine, and that we had to do some more research before we could figure out what to do.  Monday, we were told that the dog's leg would have to go.  They don't know what it is yet, but the risks of leaving the leg attached are too great.

I am now sitting in my chair in the living room, typing this out, with my dog lying in the corner on the floor, likely because the outside cold seeping through the cracks of my old and rotten wooden balcony door is helping with the pain.  He is relatively calm (spoke too soon), mainly due to three separate kinds of painkillers that I've already administered.  I'm awake not because there's something I can do...  I'm awake, because this is the last night my dog is going to have all four of his limbs.  I'm awake, because he might not survive tomorrow's surgery, and I want to have a chance to say goodbye.  The worst aspect of this, to me, at least, is that this choice to amputate his leg is not the end of the story.

It could be that he has a low-grade tumour, which we caught relatively early.  In that case, I'd be raising a three legged three-year-old dog that is mostly healthy, in that he doesn't have a life-threatening condition.  It could be that this is a high-grade tumour.  In that case, the amputation is going to buy us another month free from the suffering that he's in right now.  May be more, but not by much.  A third possibility, which I deem the most likely, is that the biopsy results would be inconclusive (again), and we would not know how much time we have.  When we find out, it'd be too late to administer treatment, but it would not be so quick as to take his life without making both him and us suffer.

Why did it have to be /my/ dog?  Well, life is, as a matter of fact, a big joke.  It'd be rather funny if someone who has /just/ come off the deep end of a protracted battle with cancer that not even for a moment relented, had their pet friend that has repeatedly helped them through the process get an astronomically improbable, incurable type of cancer, and bumbling idiots that cannot diagnose it for the better part of two months.  I have come to appreciate the humour of this situation, though I am mostly left picking up the pieces, feeling responsible for an invasive non-treatment for a cancer that I did not give him.

It's a great shame, that the same great prankster does not wish to give Mr.  ---- ------ Fournier's gangrene.  It's been done before...  and quite frankly not nearly as funny as what I have to deal with.  I am at a point where this is no longer depressing.  
* Footnotes

[fn:1]The park that is right next to my house was one well-known oligarch's property, that has recently decayed to the point of danger.  Still, at the time, broken tile flooring was considered an acceptable compromise, as the next best place to walk the dog was a great deal further away.
