#+TITLE: Sirius, two weeks fater
#+AUTHOR: Aleksandr Petrosyan
#+DATE: 2026-06-01
#+TAGS: Sirius
#+TAGS: Personal

This is a short update to the people that keep an eye on this blog.  Of course, you could /just ask/ how I'm doing.  Trouble is that I might not be completely as honest, because most of the time, that question just there for the sake of being polite.

I am not doing fine.

Two weeks ago, it felt surreal.  It felt like the dog was away, but we would get him back, just like we did when we had to cut off his leg.  That he would be drowsy and tipsy and maybe deprive me of sleep for another two weeks, but /crucially/ that he would come back.  That feeling wore off pretty quickly, even though the habits didn't.  The first day that he was gone I took his liver and gave it away to the dogs that he used to call friends.  But I've been refilling his water almost every day since, until last Friday I figured out that this wasn't helpful.  When doing groceries today, I shouted "Sirius! Walkies!" like I used to.  

I got regular episodes of ugly crying.  Over the two weeks they have neither reduced in intensity  nor frequency.  Today marks the second week.  Tomorrow marks the longest we've been apart since I got him. Next week would have been his third birthday. 

* Where this is going

There are mainly three schools of thought on how this can progress.  

A vocal punchable majority seems to believe that this is just a dog.  That I am overreacting.  Crucially, that I should have thrown Sirius out as soon as he got the cancer diagnosis.  I /should/ get a dog, because what I'm missing is /a/ dog in my life.

The second school of thought, and one I'd rather be right, says that it hurts now, but it will get better with time.  That I cannot replace /the/ dog, but I need to move on, and that I can.  And that I will get /a/ dog, that isn't going to replace Sirius, but one that will evetually fill my life just as much as he did, and make me just as sad when it comes to an end, inevitably so. 

The sad part is that there is a third school of thought.  That is the one that seems to be most consistent with my observations up to now.   It will never get better.  You lost a family member, and you will never forget him.  The pain will be just as sharp as it is today.  You will learn to live with it... or not.  And the "or not" branch seems to be where I'm headed. 

* What I lost

I lost a child.  I lost a friend.  I lost a companion that I spent a lot of time with.  I lost a big chunk of my day-to-day and the best part of the last three.  I held off on both relocation and doing a PhD because I wanted to have this form of happiness.  And now it's all gone. 

Walking a Griffon Husky mix requires a great deal of effort.  I had to walk with him at least twice a day (and given the opportunity I often walked more than four times), each being a long trek, with a great deal of forethought and planning.  Coming back meant giving him food: typically beef cooked over slow heat, and put into raised bowls.  Then he would play.  In the strictest sense, playing with him was not an enjoyable activity.  I am not a very mobile person, and I never particularly enjoyed physical activities that dogs like to engage in.

Yet over the years I found I never really shied away from them.  Maybe early on his sharp teeth posed a problem, and I was trying to protect my hands from damage.  But getting him intellectually engaged, giving him a problem to solve was something I used to do proactively, not just reactively.

There isn't a single room in this house that doesn't have something associated to him.  Right now, glancing over my desk I can see his goose, alongside two large crates of toys.  There's some toys, like the goose that didn't fit inside those crates, so they are left outside.  In my bedroom, there's an armchair.  We put that armchair in the bedroom because we wanted for him to sleep there.  He often chose to sleep on the floor next to me, and there's a ramp I wanted to build, because without one hind leg, he had trouble getting on the bed.  Kitchen?  Every time I have to cook chicken I'm reminded of his enthusiasm for that particular kind of meat.  Fish is utterly ruined for me, because every time I eat it, I get flashbacks to the time when I fed him. 

Fib, the editor I discontinued, is a reminder of the uncertainty that I had experienced.  Abandoning it feels like the decision to euthanise Sirius.  Not abandoning it, feels like the decision to kick him out.  Maybe that is why I decided to strip it for parts.

I miss my dog.  A lot.  It's a void that I don't think anything can fill.  And for the first time in a long time I'm going to admit to the fact that I'm depressed.